const constructions = [
    // {
    //     id: 5,
    //     name: "Baroque 5",
    //     url: "baroque5",
    //     mainImage: "/construction/baroque8.jpg",
    //     firstImage: "/projects/baroque 5/1.jpg",
    //     totalImages: 6,
    //     allImages: [],
    //     client: "Abolfazl Shahi",
    //     location: "Emamat 22st. 66no. Mashhad, Iran",
    //     year: "2021",
    //     area: "1000m2",
    //     type: "Residential",
    //     status: "Completed",
    //     architect: "Ali Yasini",
    //     contractor: "Reza Azad",
    //     description: "This is a description of the project",
    //     awards: "This is a description of the project",
    //     press: "This is a description of the project",
    //     team: "This is a description of the project",
    //     collaborators: "This is a description of the project",
    //     photography: "Alireza Refaee",
    // },
    // {
    //     id: 6,
    //     name: "Baroque 6",
    //     url: "baroque6",
    //     mainImage: "/construction/baroque9.jpg",
    //     firstImage: "/projects/baroque 6/1.jpg",
    //     totalImages: 6,
    //     allImages: [],
    //     client: "Abolfazl Shahi",
    //     location: "Emamat 22st. 66no. Mashhad, Iran",
    //     year: "2021",
    //     area: "1000m2",
    //     type: "Residential",
    //     status: "Completed",
    //     architect: "Ali Yasini",
    //     contractor: "Reza Azad",
    //     description: "This is a description of the project",
    //     awards: "This is a description of the project",
    //     press: "This is a description of the project",
    //     team: "This is a description of the project",
    //     collaborators: "This is a description of the project",
    //     photography: "Alireza Refaee",
    // },
    // {
    //     id: 7,
    //     name: "Baroque 7",
    //     url: "baroque7",
    //     mainImage: "/projects/baroque7.jpg",
    //     firstImage: "/projects/baroque 7/1.jpg",
    //     totalImages: 6,
    //     allImages: [],
    //     client: "Abolfazl Shahi",
    //     location: "Emamat 22st. 66no. Mashhad, Iran",
    //     year: "2021",
    //     area: "1000m2",
    //     type: "Residential",
    //     status: "Completed",
    //     architect: "Ali Yasini",
    //     contractor: "Reza Azad",
    //     description: "This is a description of the project",
    //     awards: "This is a description of the project",
    //     press: "This is a description of the project",
    //     team: "This is a description of the project",
    //     collaborators: "This is a description of the project",
    //     photography: "Alireza Refaee",
    // },
    {
        id: 7,
        name: "Baroque 7",
        url: "baroque7",
        mainImage: "/projects/baroque7.jpg",
        firstImage: "/projects/baroque 7/01.jpg",
        totalImages: 20,
        allImages: ["01.jpg", "02.jpg", "03.jpg", "04.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 9,
        name: "Baroque 9",
        url: "baroque9",
        mainImage: "/projects/baroque9.webp",
        firstImage: "/projects/baroque 9/1.jpg",
        allImages: ["02.jpg", "01.jpg", "03.jpg", "04.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 10,
        name: "Baroque 10",
        url: "baroque10",
        mainImage: "/projects/baroque10.webp",
        firstImage: "/projects/baroque 10/1.jpg",
        allImages: ["03.jpg", "02.jpg", "01.jpg", "04.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 11,
        name: "Baroque 11",
        url: "baroque11",
        mainImage: "/projects/baroque11.jpg",
        firstImage: "/projects/baroque 11/1.jpg",
        allImages: ["04.jpg", "02.jpg", "03.jpg", "01.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
];

export default constructions;