export const aboutTitlesDou =
{
    first: ["Modern", "Smart", "Artistic", "Beautiful", "Leading", "Innovative", "Modern", "Original", "Smart", "Artistic", "Authentic", "Leading", "Beautiful", "Authentic", "Innovative"],
    second: ["Quality", "Modern", "Durable", "Luxury", "Innovative", "Smart", "Artistic", "Persistent", "Beautiful", "Luxury", "Smart", "Quality", "Innovative", "Quality", "Artistic"]
}
export const team = [
    { lastName: "Roshanaei", firstName: "Hasan", img: "/team/0.jpg", role: "Executive manager" },
    { lastName: "Motevalli", firstName: "Amin", img: "/team/2.jpg", role: "Project manager" },
    { lastName: "Sharifi", firstName: "Masoud", img: "/team/5.jpg", role: "financial manager" },
    { lastName: "Bagherpour", firstName: "Amir", img: "/team/4.jpg", role: "Project manager" },
    { lastName: "Roshanaei", firstName: "Behzad", img: "/team/1.jpg", role: "Sales, Investment Manager" },
    { lastName: "Roshanaei", firstName: "Behnam", img: "/team/3.jpg", role: "ICT Manager" },
    { lastName: "Moezi", firstName: "Vesal", img: "/team/6.jpg", role: "Legal unit"},
    { lastName: "Farid", firstName: "Amirreza", img: "/team/8.jpg", role: "Construction manager" },
    { lastName: "Ferizi", firstName: "Sajad", img: "/team/7.jpg", role: "Administrative affairs" },
    { lastName: "Ebrahimi", firstName: "Yasaman", img: "/team/10.jpg", role: "Architectural phase 2 designer" },
    { lastName: "Shakori", firstName: "Samin", img: "/team/11.jpg", role: "Architectural designer" },
    { lastName: "Golestani", firstName: "Sara", img: "/team/9.jpg", role: "internal manager" },
    { lastName: "Choopani", firstName: "Faezeh", img: "/team/16.jpg", role: "Instagram page admin" },
    { lastName: "Emkani", firstName: "Maryam", img: "/team/13.jpg", role: "social media content creator" },
    { lastName: "Borzooei", firstName: "Farid", img: "/team/14.jpg", role: "social media content planner" },
    { lastName: "Kiyani", firstName: "Amir", img: "/team/15.jpg", role: "social media content photographer" },
    { lastName: "Refaee", firstName: "Alireza", img: "/team/12.jpg", role: "architectural photographer" },
]
export const projects = [
    {
        id: 5,
        name: "Baroque 5",
        url: "baroque5",
        mainImage: "/projects/baroque5.webp",
        firstImage: "/projects/baroque5/1.webp",
        images: {
            all: ["2.webp", "3.webp", "4.webp", "5.webp", "6.jpg"],
            real: ["2.webp", "3.webp", "4.webp", "5.webp", "6.jpg"],
        },
        en: {
            location: "Niavaran St, Mashhad, Iran",
            year: "2019",
            area: "800 m2",
            type: "Residential",
            status: "Completed",
            projectManager: ["Hasan Roshnaei Moghadam", "Behzad Roshnaei Moghadam"],
            architect: "Kerat Group",
            photography: "Alireza Refaee",
        },
        fa: {
            location: "خیابان نیاوران, مشهد, ایران",
            year: "1398",
            area: "800 مترمربع",
            type: "مسکونی",
            status: "تکمیل شده",
            projectManager: ["حسن روشنایی مقدم", "بهزاد روشنایی مقدم"],
            architect: "گروه کرات",
            photography: "علیرضا رفایی",
        },
        ar: {
            location: "شارع النیاوران, المشهد, الایران",
            year: "1440",
            area: "800 مترمربع",
            type: "سكني",
            status: "مکتمل",
            projectManager: ["حسن روشنایی مقدم", "بهزاد روشنایی مقدم"],
            architect: "قسم الکرات",
            photography: "علیرضا رفایی",
        }
    },
    {
        id: 6,
        name: "Baroque 6",
        url: "baroque6",
        mainImage: "/projects/baroque6.webp",
        firstImage: "/projects/baroque6/1.jpg",
        images: {
            all: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"],
            real: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"],
        },
        en: {
            location: "Niavaran St, Mashhad, Iran",
            year: "2020",
            area: "770m2",
            type: "Residential",
            projectManager: ["Amir Bagherpour"],
            status: "Completed",
            architect: "Kerat Group",
        },
        fa: {
            location: "خیابان نیاوران, مشهد, ایران",
            year: "1399",
            area: "770 مترمربع",
            type: "مسکونی",
            status: "تکمیل شده",
            projectManager: ["امیر باقرپور"],
            architect: "گروه کرات",
            photography: "علیرضا رفایی",
        },
        ar: {
            location: "شارع النیاوران, المشهد, الایران",
            year: "1441",
            area: "770 مترمربع",
            type: "سكني",
            status: "مکتمل",
            projectManager: ["امیر باقرپور"],
            architect: "قسم الکرات",
            photography: "علیرضا رفایی",
        }
    },
    {
        id: 7,
        name: "Baroque 7",
        url: "baroque7",
        mainImage: "/projects/baroque7.webp",
        firstImage: "/projects/baroque7/01.jpg",
        images: {
            all: ["02.jpg", "03.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg", "11.jpg", "3d/1.jpg", "3d/2.jpg", "3d/3.jpg", "3d/4.jpg", "3d/5.jpg", "plan/1.jpg", "plan/2.jpg", "plan/3.jpg"],
            real: ["02.jpg", "03.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg", "11.jpg"],
            art: ["3d/1.jpg", "3d/2.jpg", "3d/3.jpg", "3d/4.jpg", "3d/5.jpg"],
            plan: ["plan/1.jpg", "plan/2.jpg", "plan/3.jpg",],
            construction: ["construction/1.jpg", "construction/2.jpg", "construction/3.jpg"]
        },
        en: {
            location: "Honarestan St, Mashhad, Iran",
            year: "2020",
            area: "850m2",
            type: "Residential",
            projectManager: ["Amir Bagherpour", "Amin Motevali "],
            status: "Completed",
            architect: "Kerat Group",
            photography: "Alireza Refaee"
        },
        fa: {
            location: "خیابان هنرستان, مشهد, ایران",
            year: "1399",
            area: "850 مترمربع",
            type: "مسکونی",
            status: "تکمیل شده",
            projectManager: ["امیر باقرپور", "امین متولی"],
            architect: "گروه کرات",
            photography: "علیرضا رفایی",
        },
        ar: {
            location: "شارع الهنرستان, المشهد, الایران",
            year: "1441",
            area: "850 مترمربع",
            type: "سكني",
            status: "مکتمل",
            projectManager: ["امیر باقرپور", "امین متولی"],
            architect: "قسم الکرات",
            photography: "علیرضا رفایی",
        }
    },
    {
        id: 8,
        name: "Baroque 8",
        url: "baroque8",
        mainImage: "/projects/baroque8.webp",
        firstImage: "/projects/baroque8/4.jpg",
        images: {
            all: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "3d/1.jpg", "3d/2.jpg", "3d/3.jpg", "3d/4.jpg", "3d/5.jpg", "3d/6.jpg", "3d/7.jpg", "3d/8.jpg", "3d/9.jpg", "3d/10.jpg", "plan/1.jpg", "plan/2.jpg", "plan/3.jpg",],
            real: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg",],
            art: ["3d/1.jpg", "3d/2.jpg", "3d/3.jpg", "3d/4.jpg", "3d/5.jpg", "3d/6.jpg", "3d/7.jpg", "3d/8.jpg", "3d/9.jpg", "3d/10.jpg"],
            plan: ["plan/1.jpg", "plan/2.jpg", "plan/3.jpg",],
            construction: ["construction/1.jpg", "construction/2.jpg", "construction/3.jpg", "construction/4.jpg", "construction/5.jpg", "construction/6.jpg"]
        },
        en: {
            location: "Ladan St, Mashhad, Iran",
            year: "2020",
            area: "1000m2",
            type: "Residential",
            projectManager: ["Behnam Roshanaei Moghadam", "Amin Motevali "],
            status: "Completed",
            architect: "Kerat Group",
            photography: "Alireza Refaee"
        },
        fa: {
            location: "خیابان لادن, مشهد, ایران",
            year: "1399",
            area: "1000 مترمربع",
            type: "مسکونی",
            status: "تکمیل شده",
            projectManager: ["بهنام روشنایی مقدم", "امین متولی"],
            architect: "گروه کرات",
            photography: "علیرضا رفایی",
        },
        ar: {
            location: "شارع اللادن, المشهد, الایران",
            year: "1441",
            area: "1000 مترمربع",
            type: "سكني",
            status: "مکتمل",
            projectManager: ["بهنام روشنایی مقدم", "امین متولی"],
            architect: "قسم الکرات",
            photography: "علیرضا رفایی",
        }
    },
    {
        id: 9,
        name: "Baroque 9",
        url: "baroque9",
        mainImage: "/projects/baroque9.webp",
        firstImage: "/projects/baroque9/1.jpg",
        images: {
            all: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg", "20.jpg", "21.jpg", "22.jpg", "3d/1.jpg", "3d/2.jpg", "3d/3.jpg", "3d/4.jpg", "3d/5.jpg", "3d/6.jpg", "3d/7.jpg", "3d/8.jpg", "3d/9.jpg", "3d/10.jpg", "3d/11.jpg", "3d/12.jpg", "3d/13.jpg", "3d/5.jpg", "plan/1.jpg", "plan/2.jpg", "plan/3.jpg", "plan/4.jpg"],
            real: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg", "20.jpg", "21.jpg", "22.jpg"],
            art: ["3d/1.jpg", "3d/2.jpg", "3d/3.jpg", "3d/4.jpg", "3d/5.jpg", "3d/6.jpg", "3d/7.jpg", "3d/8.jpg", "3d/9.jpg", "3d/10.jpg", "3d/11.jpg", "3d/12.jpg", "3d/13.jpg",],
            plan: ["plan/1.jpg", "plan/2.jpg", "plan/3.jpg", "plan/4.jpg"],
            construction: ["construction/1.jpg", "construction/2.jpg"]
        },
        en: {
            location: "Mousavi Ghouchani St, Mashhad, Iran",
            year: "2021",
            area: "1700m2",
            type: "Residential",
            projectManager: ["Amir Bagherpour", "Amin Motevali "],
            status: "Completed",
            architect: "Kerat Group",
            photography: "Alireza Refaee"
        },
        fa: {
            location: "خیابان موسوی قوچانی, مشهد, ایران",
            year: "1400",
            area: "1700 مترمربع",
            type: "مسکونی",
            status: "تکمیل شده",
            projectManager: ["امیر باقرپور", "امین متولی"],
            architect: "گروه کرات",
            photography: "علیرضا رفایی",
        },
        ar: {
            location: "شارع الموسوی قوجانی, المشهد, الایران",
            year: "1442",
            area: "1700 مترمربع",
            type: "سكني",
            status: "مکتمل",
            projectManager: ["امیر باقرپور", "امین متولی"],
            architect: "قسم الکرات",
            photography: "علیرضا رفایی",
        }
    },
    {
        id: 10,
        name: "Baroque 10",
        url: "baroque10",
        mainImage: "/projects/baroque10.webp",
        firstImage: "/projects/baroque10/1.jpg",
        images: {
            all: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg", "20.jpg", "21.jpg", "3d/1.jpg", "3d/2.jpg", "3d/3.jpg", "3d/4.jpg", "3d/5.jpg", "3d/6.jpg", "plan/1.jpg", "plan/2.jpg", "plan/3.jpg"],
            real: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg", "20.jpg", "21.jpg"],
            art: ["3d/1.jpg", "3d/2.jpg", "3d/3.jpg", "3d/4.jpg", "3d/5.jpg", "3d/6.jpg"],
            plan: ["plan/1.jpg", "plan/2.jpg", "plan/3.jpg",],
            construction: ["construction/1.jpg", "construction/2.jpg", "construction/3.jpg", "construction/4.jpg", "construction/5.jpg", "construction/6.jpg", "construction/7.jpg", "construction/8.jpg", "construction/9.jpg",]
        },
        en: {
            location: "Golshan St, Mashhad, Iran",
            year: "2022",
            area: "1120m2",
            type: "Residential",
            projectManager: ["Amir Bagherpour", "Amin Motevali "],
            status: "Completed",
            architect: "Kerat Group",
            photography: "Alireza Refaee"
        },
        fa: {
            location: "خیابان گلشن, مشهد, ایران",
            year: "1401",
            area: "1120 مترمربع",
            type: "مسکونی",
            status: "تکمیل شده",
            projectManager: ["امیر باقرپور", "امین متولی"],
            architect: "گروه کرات",
            photography: "علیرضا رفایی",
        },
        ar: {
            location: "شارع الجلشن, المشهد, الایران",
            year: "1443",
            area: "1120 مترمربع",
            type: "سكني",
            status: "مکتمل",
            projectManager: ["امیر باقرپور", "امین متولی"],
            architect: "قسم الکرات",
            photography: "علیرضا رفایی",
        }
    },
    {
        id: 11,
        name: "Baroque 11",
        url: "baroque11",
        mainImage: "/projects/baroque11.webp",
        firstImage: "/projects/baroque11/1.jpg",
        images: {
            all: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg", "20.jpg", "21.jpg", "22.jpg", "23.jpg", "24.jpg", "25.jpg", "26.jpg", "plan/1.jpg", "plan/2.jpg", "plan/3.jpg",],
            real: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg", "20.jpg", "21.jpg", "22.jpg", "23.jpg", "24.jpg", "25.jpg", "26.jpg"],
            plan: ["plan/1.jpg", "plan/2.jpg", "plan/3.jpg",],
            construction: ["construction/3.jpg", "construction/4.jpg", "construction/5.jpg", "construction/6.jpg", "construction/7.jpg", "construction/8.jpg"]
        },
        en: {
            location: "Samaniye St, Mashhad, Iran",
            year: "2020",
            area: "1480m2",
            type: "Residential",
            projectManager: ["Amin Motevali"],
            status: "In Progress",
            architect: "Kerat Group",
            photography: "Alireza Refaee"
        },
        fa: {
            location: "خیابان سامانیه, مشهد, ایران",
            year: "1399",
            area: "1480 مترمربع",
            type: "مسکونی",
            status: "دردست ساخت",
            projectManager: ["امین متولی"],
            architect: "گروه کرات",
            photography: "علیرضا رفایی",
        },
        ar: {
            location: "شارع السامانیه, المشهد, الایران",
            year: "1441",
            area: "1480 مترمربع",
            type: "سكني",
            status: "تحت التشيد",
            projectManager: ["امین متولی"],
            architect: "قسم الکرات",
            photography: "علیرضا رفایی",
        }
    },
    {
        id: 12,
        name: "Baroque 12",
        url: "baroque12",
        mainImage: "/projects/baroque12.webp",
        firstImage: "/projects/baroque12/1.jpg",
        images: {
            all: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "3d/1.jpg", "3d/2.jpg", "3d/3.jpg", "3d/4.jpg", "3d/5.jpg", "3d/6.jpg", "3d/7.jpg", "3d/8.jpg", "3d/9.jpg", "3d/10.jpg", "3d/11.jpg", "3d/12.jpg", "plan/1.jpg"],
            real: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg"],
            art: ["3d/1.jpg", "3d/2.jpg", "3d/3.jpg", "3d/4.jpg", "3d/5.jpg", "3d/6.jpg", "3d/7.jpg", "3d/8.jpg", "3d/9.jpg", "3d/10.jpg", "3d/11.jpg", "3d/12.jpg"],
            plan: ["plan/1.jpg"],
            construction: ["construction/2.jpg", "construction/3.jpg", "construction/4.jpg", "construction/5.jpg", "construction/6.jpg"]
        },
        en: {
            location: "Kahou Village, Mashhad, Iran",
            year: "2022",
            area: "1120m2",
            type: "Residential",
            projectManager: ["Behnam Roshanaei Moghadam", "Amin Motevali"],
            status: "Completed",
            architect: "Kerat Group",
            photography: "Alireza Refaee"
        },
        fa: {
            location: "روستای کاهو, مشهد, ایران",
            year: "1401",
            area: "1120 مترمربع",
            type: "مسکونی",
            status: "تکمیل شده",
            projectManager: ["بهنام روشنایی مقدم", "امین متولی"],
            architect: "گروه کرات",
            photography: "علیرضا رفایی",
        },
        ar: {
            location: "قرية الکاهو, المشهد, الایران",
            year: "1443",
            area: "1120 مترمربع",
            type: "سكني",
            status: "مکتمل",
            projectManager: ["بهنام روشنایی مقدم", "امین متولی"],
            architect: "قسم الکرات",
            photography: "علیرضا رفایی",
        }
    },
    {
        id: 13,
        name: "Baroque 13",
        url: "baroque13",
        mainImage: "/projects/baroque13.webp",
        firstImage: "/projects/baroque13/1.jpeg",
        images: {
            all: ["2.jpeg", "3.jpeg", "4.jpeg", "5.jpeg", "6.jpeg", "7.jpeg", "8.jpeg", "9.jpeg", "10.jpeg", "11.jpeg", "12.jpeg", "13.jpeg", "14.jpeg", "15.jpeg", "16.jpeg",],
            real: ["2.jpeg", "3.jpeg", "4.jpeg", "5.jpeg", "6.jpeg", "7.jpeg", "8.jpeg", "9.jpeg", "10.jpeg", "11.jpeg", "12.jpeg", "13.jpeg", "14.jpeg", "15.jpeg", "16.jpeg"],
            construction: ["construction/1.jpg", "construction/2.jpg", "construction/3.jpg", "construction/4.jpg", "construction/5.jpg"]
        },
        en: {
            location: "Emam Reza St., Shandiz, Mashhad, Iran",
            year: "2023",
            area: "1100m2",
            type: "Residential",
            projectManager: ["Amir Bagherpour"],
            status: "In Progress",
            architect: "Kerat Group",
            photography: "Alireza Refaee"
        },
        fa: {
            location: "خیابان امام رضا, شاندیز, مشهد, ایران",
            year: "1402",
            area: "1100 مترمربع",
            type: "مسکونی",
            status: "دردست ساخت",
            projectManager: ["امیر باقرپور"],
            architect: "گروه کرات",
            photography: "علیرضا رفایی",
        },
        ar: {
            location: "شارع الامام الرضا, الشاندیز, المشهد, الایران",
            year: "1444",
            area: "1100 مترمربع",
            type: "سكني",
            status: "تحت التشيد",
            projectManager: ["امیر باقرپور"],
            architect: "قسم الکرات",
            photography: "علیرضا رفایی",
        }
    },
    {
        id: 14,
        name: "Baroque 14",
        url: "baroque14",
        mainImage: "/projects/baroque14.webp",
        firstImage: "/projects/baroque14/1.jpg",
        images: {
            all: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"],
            real: ["2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"],
            construction: ["construction/1.jpg", "construction/2.jpg", "construction/3.jpg", "construction/4.jpg", "construction/5.jpg", "construction/6.jpg"]
        },
        en: {
            location: "Honarestan St., Mashhad, Iran",
            year: "2023",
            area: "1115m2",
            type: "Residential",
            projectManager: ["Amir Bagherpour"],
            status: "In Progress",
            architect: "Kerat Group",
            photography: "Alireza Refaee"
        },
        fa: {
            location: "خیابان هنرستان, مشهد, ایران",
            year: "1402",
            area: "1115 مترمربع",
            type: "مسکونی",
            status: "دردست ساخت",
            projectManager: ["امیر باقرپور"],
            architect: "گروه کرات",
            photography: "علیرضا رفایی",
        },
        ar: {
            location: "شارع الهنرستان, المشهد, الایران",
            year: "1444",
            area: "1115 مترمربع",
            type: "سكني",
            status: "تحت التشيد",
            projectManager: ["امیر باقرپور"],
            architect: "قسم الکرات",
            photography: "علیرضا رفایی",
        }
    },
    {
        id: 15,
        name: "Baroque 15",
        url: "baroque15",
        mainImage: "/projects/baroque15.webp",
        firstImage: "/projects/baroque15/3.jpeg",
        images: {
            all: ["1.jpeg", "2.jpeg"],
            real: ["1.jpeg", "2.jpeg"],
            construction: ["construction/1.jpeg", "construction/2.jpeg", "construction/3.jpeg"]
        },
        en: {
            location: "Hashemiye St., Mashhad, Iran",
            year: "2023",
            area: "734m2",
            type: "Residential",
            projectManager: ["Amin Motevali "],
            status: "In Progress",
            architect: "Baroque Architectural studio",
            photography: "Alireza Refaee"
        },
        fa: {
            location: "خیابان هاشمیه, مشهد, ایران",
            year: "1402",
            area: "734 مترمربع",
            type: "مسکونی",
            status: "دردست ساخت",
            projectManager: ["امین متولی"],
            architect: "دفتر مهندسی باروک",
            photography: "علیرضا رفایی",
        },
        ar: {
            location: "شارع الهاشمیه, المشهد, الایران",
            year: "1444",
            area: "734 مترمربع",
            type: "سكني",
            status: "تحت التشيد",
            projectManager: ["امین متولی"],
            architect: "استوديو المعمارية الباروک",
            photography: "علیرضا رفایی",
        }
    }
];

export const projectsReversed = projects.reverse()
