const projects = [
    {
        id: 5,
        name: "Baroque 5",
        url: "baroque5",
        mainImage: "/projects/baroque5.jpg",
        firstImage: "/projects/baroque5/1.jpg",
        totalImages: 6,
        allImages: ["1"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 6,
        name: "Baroque 6",
        url: "baroque6",
        mainImage: "/projects/baroque6.jpg",
        firstImage: "/projects/baroque6/1.jpg",
        totalImages: 6,
        allImages: [],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 7,
        name: "Baroque 7",
        url: "baroque7",
        mainImage: "/projects/baroque7.jpg",
        firstImage: "/projects/baroque7/01.jpg",
        totalImages: 20,
        allImages: ["02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg", "11.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 8,
        name: "Baroque 8",
        url: "baroque8",
        mainImage: "/projects/baroque8.webp",
        firstImage: "/projects/baroque8/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2022",
        area: "1000m2",
        type: "Commercial",
        status: "In Progress",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 9,
        name: "Baroque 9",
        url: "baroque9",
        mainImage: "/projects/baroque9.webp",
        firstImage: "/projects/baroque9/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 10,
        name: "Baroque 10",
        url: "baroque10",
        mainImage: "/projects/baroque10.webp",
        firstImage: "/projects/baroque10/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 11,
        name: "Baroque 11",
        url: "baroque11",
        mainImage: "/projects/baroque11.jpg",
        firstImage: "/projects/baroque11/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 12,
        name: "Baroque 12",
        url: "baroque12",
        mainImage: "/projects/baroque12.jpg",
        firstImage: "/projects/baroque11/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 11,
        name: "Baroque 13",
        url: "baroque13",
        mainImage: "/projects/baroque13.jpg",
        firstImage: "/projects/baroque13/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 14,
        name: "Baroque 14",
        url: "baroque14",
        mainImage: "/projects/baroque14.jpg",
        firstImage: "/projects/baroque14/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    }
];

export default projects;