const projects = [
    {
        id: 1,
        name: "Baroque 1",
        url: "baroque1",
        mainImage: "/projects/baroque1.jpg",
        startDate: `95/07/01`,
        endDate: `96/03/01`,
        constDate: 9,
        firstImage: "/projects/baroque 1/1.jpg",
        totalImages: 6,
        allImages: ["1.jpg", "2.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: 2017,
        area: 750,
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 2,
        name: "Baroque 2",
        url: "baroque2",
        mainImage: "/projects/baroque2.jpg",
        firstImage: "/projects/baroque 2/1.jpg",
        totalImages: 6,
        allImages: ["01.jpg", "03.jpeg", "04.jpeg", "05.jpg", "06.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 3,
        name: "Baroque 3",
        url: "baroque3",
        mainImage: "/projects/baroque3.jpg",
        firstImage: "/projects/baroque 3/1.jpg",
        totalImages: 6,
        allImages: ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 4,
        name: "Baroque 4",
        url: "baroque4",
        mainImage: "/projects/baroque4.webp",
        firstImage: "/projects/baroque 4/1.jpg",
        totalImages: 6,
        allImages: ["1", "2", "3", "4", "5", "6", "7"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 5,
        name: "Baroque 5",
        url: "baroque5",
        mainImage: "/projects/baroque5.jpg",
        firstImage: "/projects/baroque 5/1.jpg",
        totalImages: 6,
        allImages: ["1"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 6,
        name: "Baroque 6",
        url: "baroque6",
        mainImage: "/projects/baroque6.jpg",
        firstImage: "/projects/baroque 6/1.jpg",
        totalImages: 6,
        allImages: [],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 7,
        name: "Baroque 7",
        url: "baroque7",
        mainImage: "/projects/baroque7.jpg",
        firstImage: "/projects/baroque 7/01.jpg",
        totalImages: 20,
        allImages: ["02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg", "11.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 8,
        name: "Baroque 8",
        url: "baroque8",
        mainImage: "/projects/baroque8.webp",
        firstImage: "/projects/baroque 8/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2022",
        area: "1000m2",
        type: "Commercial",
        status: "In Progress",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 9,
        name: "Baroque 9",
        url: "baroque9",
        mainImage: "/projects/baroque9.webp",
        firstImage: "/projects/baroque 9/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 10,
        name: "Baroque 10",
        url: "baroque10",
        mainImage: "/projects/baroque10.webp",
        firstImage: "/projects/baroque 10/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 11,
        name: "Baroque 11",
        url: "baroque11",
        mainImage: "/projects/baroque11.jpg",
        firstImage: "/projects/baroque 11/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 12,
        name: "Baroque 12",
        url: "baroque12",
        mainImage: "/projects/baroque12.jpg",
        firstImage: "/projects/baroque 11/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 11,
        name: "Baroque 13",
        url: "baroque13",
        mainImage: "/projects/baroque13.jpg",
        firstImage: "/projects/baroque 13/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    },
    {
        id: 14,
        name: "Baroque 14",
        url: "baroque14",
        mainImage: "/projects/baroque14.jpg",
        firstImage: "/projects/baroque 14/1.jpg",
        allImages: ["/placeholder.jpg"],
        client: "Abolfazl Shahi",
        location: "Emamat 22st. 66no. Mashhad, Iran",
        year: "2021",
        area: "1000m2",
        type: "Residential",
        status: "Completed",
        architect: "Ali Yasini",
        contractor: "Reza Azad",
        description: "This is a description of the project",
        awards: "This is a description of the project",
        press: "This is a description of the project",
        team: "This is a description of the project",
        collaborators: "This is a description of the project",
        photography: "Alireza Refaee",
    }
];

export default projects;